[2022-05-30 20:21:30,249] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:30,509] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:30,520] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:30,522] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:21:30,523] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:30,813] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-04-02 06:00:00+00:00
[2022-05-30 20:21:30,986] {standard_task_runner.py:52} INFO - Started process 1299 to run task
[2022-05-30 20:21:31,352] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp96inbxul', '--error-file', '/tmp/tmpjje4_596']
[2022-05-30 20:21:31,433] {standard_task_runner.py:80} INFO - Job 138: Subtask ingest
[2022-05-30 20:21:32,925] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:21:34,694] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:21:36,813] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2022-05-30 20:21:36,845] {logging_mixin.py:115} INFO - yellow_taxi_2021_04 /opt/***/output_2021-04.parquet 2021-04-02T06:00:00+00:00
[2022-05-30 20:21:36,865] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:21:37,085] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210402T060000, start_date=20220530T202130, end_date=20220530T202137
[2022-05-30 20:21:37,374] {standard_task_runner.py:97} ERROR - Failed to execute job 138 for task ingest (invalid literal for int() with base 10: 'None'; 1299)
[2022-05-30 20:21:37,669] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-30 20:21:38,929] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:18:11,602] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-05-30 22:18:11,660] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-05-30 22:18:11,663] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:18:11,667] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:18:11,668] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:18:11,750] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-04-02 06:00:00+00:00
[2022-05-30 22:18:11,798] {standard_task_runner.py:52} INFO - Started process 1469 to run task
[2022-05-30 22:18:11,835] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpe769s4yv', '--error-file', '/tmp/tmp3bcxptrm']
[2022-05-30 22:18:11,839] {standard_task_runner.py:80} INFO - Job 226: Subtask ingest
[2022-05-30 22:18:12,091] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:18:12,303] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:18:12,526] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2022-05-30 22:18:12,537] {logging_mixin.py:115} INFO - yellow_taxi_2021_04 /opt/***/output_2021-04.parquet 2021-04-02T06:00:00+00:00
[2022-05-30 22:18:12,633] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:19:00,157] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:19:00,193] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210402T060000, start_date=20220530T221811, end_date=20220530T221900
[2022-05-30 22:19:00,247] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:20:57,883] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-05-30 22:20:57,894] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-05-30 22:20:57,895] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:20:57,896] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:20:57,897] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:20:57,913] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-04-02 06:00:00+00:00
[2022-05-30 22:20:57,926] {standard_task_runner.py:52} INFO - Started process 1711 to run task
[2022-05-30 22:20:57,930] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp8wrmy8kr', '--error-file', '/tmp/tmpibsqvedc']
[2022-05-30 22:20:57,934] {standard_task_runner.py:80} INFO - Job 245: Subtask ingest
[2022-05-30 22:20:58,000] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:20:58,043] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:20:58,079] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2022-05-30 22:20:58,081] {logging_mixin.py:115} INFO - yellow_taxi_2021_04 /opt/***/output_2021-04.parquet 2021-04-02T06:00:00+00:00
[2022-05-30 22:20:58,124] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:21:17,776] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:21:18,108] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210402T060000, start_date=20220530T222057, end_date=20220530T222117
[2022-05-30 22:21:19,407] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
