[2022-05-30 20:21:40,398] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:40,710] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:40,725] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:40,732] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:21:40,737] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:41,441] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-02-02 06:00:00+00:00
[2022-05-30 20:21:41,572] {standard_task_runner.py:52} INFO - Started process 1309 to run task
[2022-05-30 20:21:41,602] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp8zy61w21', '--error-file', '/tmp/tmppmr4sq56']
[2022-05-30 20:21:41,618] {standard_task_runner.py:80} INFO - Job 145: Subtask ingest
[2022-05-30 20:21:42,470] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:21:42,747] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:21:42,978] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-05-30 20:21:43,002] {logging_mixin.py:115} INFO - yellow_taxi_2021_02 /opt/***/output_2021-02.parquet 2021-02-02T06:00:00+00:00
[2022-05-30 20:21:43,008] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:21:43,071] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210202T060000, start_date=20220530T202140, end_date=20220530T202143
[2022-05-30 20:21:43,144] {standard_task_runner.py:97} ERROR - Failed to execute job 145 for task ingest (invalid literal for int() with base 10: 'None'; 1309)
[2022-05-30 20:21:43,348] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-30 20:21:43,592] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:16:49,072] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-05-30 22:16:49,108] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-05-30 22:16:49,110] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:16:49,117] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:16:49,119] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:16:49,170] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-02-02 06:00:00+00:00
[2022-05-30 22:16:49,226] {standard_task_runner.py:52} INFO - Started process 1331 to run task
[2022-05-30 22:16:49,292] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpm2tiyfp3', '--error-file', '/tmp/tmpuxue2fh3']
[2022-05-30 22:16:49,301] {standard_task_runner.py:80} INFO - Job 214: Subtask ingest
[2022-05-30 22:16:49,452] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:16:49,541] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:16:49,708] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-05-30 22:16:49,717] {logging_mixin.py:115} INFO - yellow_taxi_2021_02 /opt/***/output_2021-02.parquet 2021-02-02T06:00:00+00:00
[2022-05-30 22:16:49,864] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:17:15,483] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:17:15,609] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210202T060000, start_date=20220530T221649, end_date=20220530T221715
[2022-05-30 22:17:15,805] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:21:50,831] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-05-30 22:21:51,286] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-05-30 22:21:51,299] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:21:51,305] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:21:51,306] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:21:51,902] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-02-02 06:00:00+00:00
[2022-05-30 22:21:53,834] {standard_task_runner.py:52} INFO - Started process 1823 to run task
[2022-05-30 22:21:54,557] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp8gtm99hl', '--error-file', '/tmp/tmp0rwsr5rd']
[2022-05-30 22:21:55,114] {standard_task_runner.py:80} INFO - Job 255: Subtask ingest
[2022-05-30 22:22:07,475] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-02-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:22:09,511] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:22:10,150] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-05-30 22:22:10,251] {logging_mixin.py:115} INFO - yellow_taxi_2021_02 /opt/***/output_2021-02.parquet 2021-02-02T06:00:00+00:00
[2022-05-30 22:22:10,432] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:23:58,067] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-30 22:24:00,401] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1823. PIDs of all processes in the group: [1823]
[2022-05-30 22:24:00,414] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1823
[2022-05-30 22:25:00,504] {process_utils.py:143} WARNING - process psutil.Process(pid=1823, name='airflow task ru', status='running', started='22:21:52') did not respond to SIGTERM. Trying SIGKILL
[2022-05-30 22:25:01,742] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 1823
[2022-05-30 22:25:39,294] {process_utils.py:75} INFO - Process psutil.Process(pid=1823, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='22:21:52') (1823) terminated with exit code Negsignal.SIGKILL
[2022-05-30 22:25:39,314] {standard_task_runner.py:162} ERROR - Job 255 was killed before it finished (likely due to running out of memory)
