[2022-05-31 18:49:18,588] {taskinstance.py:1154} INFO - Dependencies not met for <TaskInstance: yellow_taxi_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-01T06:00:00+00:00 [skipped]>, dependency 'Task Instance State' FAILED: Task is in the 'skipped' state.
[2022-05-31 18:49:18,601] {local_task_job.py:101} INFO - Task is not able to be run
[2022-05-31 18:56:01,724] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: yellow_taxi_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-01T06:00:00+00:00 [queued]>
[2022-05-31 18:56:01,733] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: yellow_taxi_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-01T06:00:00+00:00 [queued]>
[2022-05-31 18:56:01,734] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 18:56:01,735] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-31 18:56:01,737] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 18:56:01,748] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-05-01 06:00:00+00:00
[2022-05-31 18:56:01,753] {standard_task_runner.py:52} INFO - Started process 1558 to run task
[2022-05-31 18:56:01,757] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-05-01T06:00:00+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/yellow_taxi_ingestion.py', '--cfg-path', '/tmp/tmp_sltnq09', '--error-file', '/tmp/tmp1l3_9np0']
[2022-05-31 18:56:01,759] {standard_task_runner.py:80} INFO - Job 428: Subtask local_to_gcs_task
[2022-05-31 18:56:01,817] {task_command.py:370} INFO - Running <TaskInstance: yellow_taxi_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-01T06:00:00+00:00 [running]> on host 3f188d455d5a
[2022-05-31 18:56:01,862] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-31 18:56:01,906] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-05-01T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-01T06:00:00+00:00
[2022-05-31 18:56:06,037] {python.py:173} INFO - Done. Returned value was: None
[2022-05-31 18:56:06,081] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=yellow_taxi_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210501T060000, start_date=20220531T185601, end_date=20220531T185606
[2022-05-31 18:56:06,141] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-31 18:56:06,232] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
