[2022-05-30 20:21:30,271] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:30,467] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-05-30 20:21:30,476] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:30,480] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 20:21:30,485] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 20:21:30,729] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-05-02 06:00:00+00:00
[2022-05-30 20:21:30,972] {standard_task_runner.py:52} INFO - Started process 1300 to run task
[2022-05-30 20:21:31,602] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpwbarbq2z', '--error-file', '/tmp/tmp92fdpafm']
[2022-05-30 20:21:31,880] {standard_task_runner.py:80} INFO - Job 139: Subtask ingest
[2022-05-30 20:21:33,089] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host e083cbf9476b
[2022-05-30 20:21:33,830] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 20:21:34,972] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-05-30 20:21:35,084] {logging_mixin.py:115} INFO - yellow_taxi_2021_05 /opt/***/output_2021-05.parquet 2021-05-02T06:00:00+00:00
[2022-05-30 20:21:35,103] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 12, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 772, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2022-05-30 20:21:35,782] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210502T060000, start_date=20220530T202130, end_date=20220530T202135
[2022-05-30 20:21:36,720] {standard_task_runner.py:97} ERROR - Failed to execute job 139 for task ingest (invalid literal for int() with base 10: 'None'; 1300)
[2022-05-30 20:21:37,364] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-30 22:16:55,075] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-05-30 22:16:55,220] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-05-30 22:16:55,224] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:16:55,225] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:16:55,234] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:16:55,348] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-05-02 06:00:00+00:00
[2022-05-30 22:16:55,376] {standard_task_runner.py:52} INFO - Started process 1349 to run task
[2022-05-30 22:16:55,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpz0m0fp6a', '--error-file', '/tmp/tmpcjs13e8r']
[2022-05-30 22:16:55,413] {standard_task_runner.py:80} INFO - Job 217: Subtask ingest
[2022-05-30 22:16:55,639] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:16:55,806] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:16:55,939] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-05-30 22:16:55,948] {logging_mixin.py:115} INFO - yellow_taxi_2021_05 /opt/***/output_2021-05.parquet 2021-05-02T06:00:00+00:00
[2022-05-30 22:16:56,062] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:17:26,881] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:17:27,316] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210502T060000, start_date=20220530T221655, end_date=20220530T221727
[2022-05-30 22:17:28,177] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-30 22:21:29,964] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-05-30 22:21:30,060] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-05-30 22:21:30,061] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:21:30,064] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-30 22:21:30,066] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 22:21:30,192] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): ingest> on 2021-05-02 06:00:00+00:00
[2022-05-30 22:21:30,323] {standard_task_runner.py:52} INFO - Started process 1775 to run task
[2022-05-30 22:21:30,462] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpof4vykxd', '--error-file', '/tmp/tmp0u00dwl4']
[2022-05-30 22:21:30,490] {standard_task_runner.py:80} INFO - Job 249: Subtask ingest
[2022-05-30 22:21:31,145] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host 8ac972de2f4f
[2022-05-30 22:21:31,867] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-30 22:21:32,300] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-05-30 22:21:32,395] {logging_mixin.py:115} INFO - yellow_taxi_2021_05 /opt/***/output_2021-05.parquet 2021-05-02T06:00:00+00:00
[2022-05-30 22:21:32,506] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-05-30 22:22:26,153] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-05-30 22:22:27,572] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210502T060000, start_date=20220530T222129, end_date=20220530T222227
[2022-05-30 22:22:28,664] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
