[2022-05-31 19:15:26,874] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: fhvhv_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-01T06:00:00+00:00 [queued]>
[2022-05-31 19:15:26,909] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: fhvhv_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-01T06:00:00+00:00 [queued]>
[2022-05-31 19:15:26,918] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:26,923] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-31 19:15:26,930] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:26,956] {taskinstance.py:1378} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-03-01 06:00:00+00:00
[2022-05-31 19:15:26,981] {standard_task_runner.py:52} INFO - Started process 687 to run task
[2022-05-31 19:15:26,991] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fhvhv_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2020-03-01T06:00:00+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/fhv_ingestion.py', '--cfg-path', '/tmp/tmpjfo9eeox', '--error-file', '/tmp/tmp6fc5u06q']
[2022-05-31 19:15:26,995] {standard_task_runner.py:80} INFO - Job 467: Subtask download_dataset_task
[2022-05-31 19:15:27,168] {task_command.py:370} INFO - Running <TaskInstance: fhvhv_ingestion_gcs_dag.download_dataset_task scheduled__2020-03-01T06:00:00+00:00 [running]> on host 3f188d455d5a
[2022-05-31 19:15:27,427] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-31 19:15:27,838] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhvhv_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-03-01T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-01T06:00:00+00:00
[2022-05-31 19:15:27,852] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-31 19:15:27,881] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/fhvhv_tripdata_2020-03.parquet > /opt/***/output_fhvhv_2020-03.parquet']
[2022-05-31 19:15:27,974] {subprocess.py:85} INFO - Output:
[2022-05-31 19:15:37,309] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-31 19:15:37,332] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 687. PIDs of all processes in the group: [689, 690, 687]
[2022-05-31 19:15:37,336] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 687
[2022-05-31 19:15:37,343] {taskinstance.py:1542} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-31 19:15:37,350] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-31 19:15:37,368] {process_utils.py:75} INFO - Process psutil.Process(pid=690, status='terminated', started='19:15:27') (690) terminated with exit code None
[2022-05-31 19:15:37,549] {process_utils.py:75} INFO - Process psutil.Process(pid=687, status='terminated', exitcode=0, started='19:15:26') (687) terminated with exit code 0
[2022-05-31 19:15:37,568] {process_utils.py:75} INFO - Process psutil.Process(pid=689, status='terminated', started='19:15:27') (689) terminated with exit code None
