[2022-05-31 19:15:00,685] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: fhvhv_ingestion_gcs_dag.download_dataset_task scheduled__2020-01-01T06:00:00+00:00 [queued]>
[2022-05-31 19:15:00,728] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: fhvhv_ingestion_gcs_dag.download_dataset_task scheduled__2020-01-01T06:00:00+00:00 [queued]>
[2022-05-31 19:15:00,732] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:00,736] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-31 19:15:00,741] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:15:00,796] {taskinstance.py:1378} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-01-01 06:00:00+00:00
[2022-05-31 19:15:00,844] {standard_task_runner.py:52} INFO - Started process 653 to run task
[2022-05-31 19:15:00,906] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fhvhv_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2020-01-01T06:00:00+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/fhv_ingestion.py', '--cfg-path', '/tmp/tmpnl9k50xo', '--error-file', '/tmp/tmp9lv0jqiq']
[2022-05-31 19:15:00,914] {standard_task_runner.py:80} INFO - Job 465: Subtask download_dataset_task
[2022-05-31 19:15:01,435] {task_command.py:370} INFO - Running <TaskInstance: fhvhv_ingestion_gcs_dag.download_dataset_task scheduled__2020-01-01T06:00:00+00:00 [running]> on host 3f188d455d5a
[2022-05-31 19:15:01,837] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-05-31 19:15:02,052] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhvhv_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T06:00:00+00:00
[2022-05-31 19:15:02,074] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-31 19:15:02,089] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/fhvhv_tripdata_2020-01.parquet > /opt/***/output_fhvhv_2020-01.parquet']
[2022-05-31 19:15:02,264] {subprocess.py:85} INFO - Output:
[2022-05-31 19:15:16,210] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-05-31 19:15:16,232] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 653. PIDs of all processes in the group: [654, 655, 653]
[2022-05-31 19:15:16,236] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 653
[2022-05-31 19:15:16,241] {taskinstance.py:1542} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-31 19:15:16,245] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-31 19:15:16,414] {process_utils.py:75} INFO - Process psutil.Process(pid=653, status='terminated', exitcode=0, started='19:15:00') (653) terminated with exit code 0
[2022-05-31 19:15:16,419] {process_utils.py:75} INFO - Process psutil.Process(pid=655, status='terminated', started='19:15:01') (655) terminated with exit code None
[2022-05-31 19:15:16,420] {process_utils.py:75} INFO - Process psutil.Process(pid=654, status='terminated', started='19:15:01') (654) terminated with exit code None
