[2022-05-31 19:27:03,327] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: taxi_zones_ingestion_gcs_dag.format_to_parquet_task manual__2022-05-31T19:27:01.358447+00:00 [queued]>
[2022-05-31 19:27:03,351] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: taxi_zones_ingestion_gcs_dag.format_to_parquet_task manual__2022-05-31T19:27:01.358447+00:00 [queued]>
[2022-05-31 19:27:03,354] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:27:03,356] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-31 19:27:03,357] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 19:27:03,396] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-05-31 19:27:01.358447+00:00
[2022-05-31 19:27:03,416] {standard_task_runner.py:52} INFO - Started process 1366 to run task
[2022-05-31 19:27:03,450] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'taxi_zones_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2022-05-31T19:27:01.358447+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/taxi_zones_ingestion.py', '--cfg-path', '/tmp/tmp2erit5n_', '--error-file', '/tmp/tmpfy_cxllo']
[2022-05-31 19:27:03,463] {standard_task_runner.py:80} INFO - Job 483: Subtask format_to_parquet_task
[2022-05-31 19:27:03,807] {task_command.py:370} INFO - Running <TaskInstance: taxi_zones_ingestion_gcs_dag.format_to_parquet_task manual__2022-05-31T19:27:01.358447+00:00 [running]> on host 3f188d455d5a
[2022-05-31 19:27:04,218] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=taxi_zones_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T19:27:01.358447+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-31T19:27:01.358447+00:00
[2022-05-31 19:27:04,670] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/taxi_zones_ingestion.py", line 27, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 886, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 895, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Empty CSV file
[2022-05-31 19:27:04,732] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=taxi_zones_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20220531T192701, start_date=20220531T192703, end_date=20220531T192704
[2022-05-31 19:27:04,769] {standard_task_runner.py:97} ERROR - Failed to execute job 483 for task format_to_parquet_task (Empty CSV file; 1366)
[2022-05-31 19:27:04,860] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-31 19:27:04,977] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
